### ISSUE TITLE
Join & Quit Messages of groups are broken

### ISSUE THREAD

**Issue by magef1x** [Crazy-Crew/ChatManager#42]
### **Describe the bug**

Im using ChatManager on my setup and tested these versions for use join & quit messages of groups feature but its broken on these versions: 3.7.7, 3.8.0 BETA-3, 3.9.1+BETA, eea5b4a. Tested every version at 1.19.4 Paper and all of them are broken. 

The bug is i want to configurate a xxx rank join message but if a xxx rank player join, its joining with default join message of group.

### **Steps to reproduce**

Step 1. Install ChatManager
Step 2. Try to configurate join & quit messages of groups
Step 3. Give the correct permissions to correct groups
Step 4. Save config changes
Step 5. Restart Server & Reload Plugin
Step 6. Give the configurated group to yourself and try to join to server

**Comment by RyderBelserion** [comment]
Can you share your config.yml?

https://mclo.gs/

**Comment by magef1x** [comment]
https://mclo.gs/ymjPECq (Deleted some configurations on join & quit messages of groups. The deleted things won't solve to issue)

**Comment by ryderbelserion** [comment]
Can't reproduce
