### ISSUE TITLE
Chat color and format Bug

### ISSUE THREAD

**Issue by Gilthunderx** [Crazy-Crew/ChatManager#55]
### Server Version

1.19.4

### Server Platform

Purpur

### Describe the bug

Normal players on my server is able to use the chat color and format feature, despite not having the perm and the feature disabled on the config.

### Steps to reproduce

normally use the chat color &e&lTest and it will work without having perm.

### Additional context

https://discord.com/channels/415940589712965632/415942091059757058/1152936009793818719

I have reported this on the discord channel

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
I've fixed this issue finally, You can grab the builds on the jenkins. https://jenkins.crazycrew.us/job/ChatManager/

Make sure to check the new documentation https://docs.crazycrew.us/chatmanager/home as a few things have changed including permissions.
