### ISSUE TITLE
Chat manager exeption

### ISSUE THREAD

**Issue by Nightkau** [Crazy-Crew/ChatManager#78]
### Plugin Version

3.7.7

### Server Version

1.21.1

### Server Platform

Spigot

### Describe the bug

Chat manager shows this issue in the console repeatedly, seems to be trying to parse a word as a number?

https://pastebin.com/zTMjkyfM

### Steps to reproduce

installed chat manager on my 1.21.1 server and it does this whenever the server is online

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by Alecsou** [comment]
Same here, with Purpur in 1.21.1, 3.7.7 Plugin version

**Comment by ryderbelserion** [comment]
3.7.7 is outdated, look on modrinth

**Comment by Alecsou** [comment]
Alright, should be closed then, I confirm this is fixed in latest versions
