### ISSUE TITLE
Vanilla minecraft teams color,prefix and suffix support

### ISSUE THREAD

**Issue by jona23E** [Crazy-Crew/ChatManager#79]
### Describe the feature

As a server owner & mapmaker i was always trying to find a way to fix vanilla minecraft team /prefixes on servers for adventure maps, roleplay maps etc.
I'd greately appreciate if a config option existed to re-add these features.

multiplayer:
![image](https://github.com/user-attachments/assets/9da7b589-0656-49af-bcc6-6d2acf5f6e07)

singleplayer:
![image](https://github.com/user-attachments/assets/a0a2f357-f0f7-4f4a-92b2-97775de62e1e)

**Comment by Potatobag5823** [comment]
top
